// frontend/src/pages/ComplianceReports.tsx
import React, { useEffect, useState } from "react";
import axios from "axios";
import Header from "../components/Header";
import { useAuth } from "../context/AuthContext";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";

type ReportType = "gdpr" | "hipaa" | "pia";

const ComplianceReports: React.FC = () => {
  const { auth } = useAuth();
  const token = auth.token;

  const [datasets, setDatasets] = useState<any[]>([]);
  const [policies, setPolicies] = useState<any[]>([]);

  const [reportType, setReportType] = useState<ReportType>("gdpr");
  const [selectedDatasets, setSelectedDatasets] = useState<string[]>([]);
  const [selectedPolicies, setSelectedPolicies] = useState<string[]>([]);
  const [dateFrom, setDateFrom] = useState<string>("");
  const [dateTo, setDateTo] = useState<string>("");

  const [report, setReport] = useState<any | null>(null);
  const [loading, setLoading] = useState(false);

  const loadLists = async () => {
    try {
      const [dRes, pRes] = await Promise.all([
        axios.get(`${API_URL}/api/datasets`, { headers: { Authorization: `Bearer ${token}` } }),
        axios.get(`${API_URL}/api/policies`, { headers: { Authorization: `Bearer ${token}` } })
      ]);
      setDatasets(dRes.data || []);
      setPolicies(pRes.data || []);
    } catch (err) {
      console.error(err);
      alert("Failed to load datasets/policies");
    }
  };

  useEffect(() => {
    if (token) loadLists();
  }, [token]);

  const submitGenerate = async () => {
    try {
      setLoading(true);
      setReport(null);
      const payload: any = {
        type: reportType
      };
      if (selectedDatasets.length) payload.datasetIds = selectedDatasets;
      if (selectedPolicies.length) payload.policyIds = selectedPolicies;
      if (dateFrom) payload.dateFrom = new Date(dateFrom).toISOString();
      if (dateTo) payload.dateTo = new Date(dateTo).toISOString();

      const res = await axios.post(`${API_URL}/api/reports/generate`, payload, {
        headers: { Authorization: `Bearer ${token}` }
      });

      if (res.data?.ok) {
        setReport(res.data.report);
      } else {
        alert("Failed to generate report");
      }
    } catch (err: any) {
      console.error(err);
      alert("Error generating report: " + (err.response?.data?.message || err.message));
    } finally {
      setLoading(false);
    }
  };

  const exportPdf = () => {
    if (!report) return alert("No report to export");

    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const margin = 40;
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFontSize(14);
    doc.text(`Compliance Report - ${report.metadata.reportType.toUpperCase()}`, margin, 60);
    doc.setFontSize(10);
    doc.text(`Generated by: ${report.metadata.generatedBy}`, margin, 80);
    doc.text(`Generated at: ${new Date(report.metadata.generatedAt).toLocaleString()}`, margin, 96);
    doc.text(`Datasets: ${report.metadata.datasetCount} • Policies: ${report.metadata.policyCount} • Jobs: ${report.metadata.jobCount}`, margin, 112);

    // Findings
    doc.setFontSize(12);
    doc.text("Findings:", margin, 140);
    const findings = report.findings || [];
    if (findings.length === 0) {
      doc.setFontSize(10);
      doc.text("No automated findings.", margin, 160);
    } else {
      const yStart = 160;
      let y = yStart;
      findings.forEach((f: any, idx: number) => {
        if (y > doc.internal.pageSize.getHeight() - 100) {
          doc.addPage();
          y = margin;
        }
        doc.setFontSize(10);
        doc.text(`${idx + 1}. [${f.severity}] ${f.message}`, margin, y);
        y += 16;
      });
    }

    // Datasets table
    doc.addPage();
    doc.setFontSize(12);
    doc.text("Datasets", margin, 60);
    const dsColumns = ["ID", "Name", "Uploaded By", "Uploaded At", "Fields"];
    const dsRows = (report.datasets || []).map((d: any) => [
      String(d.id),
      d.originalName,
      d.uploadedBy,
      new Date(d.uploadedAt).toLocaleString(),
      (d.fields || []).map((f:any)=>f.name).join(", ")
    ]);
    autoTable(doc as any, {
      startY: 80,
      head: [dsColumns],
      body: dsRows,
      theme: "grid",
      styles: { fontSize: 9 }
    });

    // Policies table
    doc.addPage();
    doc.setFontSize(12);
    doc.text("Policies", margin, 60);
    const pCols = ["ID", "Name", "Dataset", "Version", "k", "l", "ε"];
    const pRows = (report.policies || []).map((p:any) => [
      String(p.id),
      p.name,
      String(p.datasetId),
      String(p.version || ""),
      String(p.k),
      String(p.l),
      String(p.epsilon)
    ]);
    autoTable(doc as any, {
      startY: 80,
      head: [pCols],
      body: pRows,
      theme: "striped",
      styles: { fontSize: 9 }
    });

    // Recent jobs
    doc.addPage();
    doc.setFontSize(12);
    doc.text("Jobs (Recent)", margin, 60);
    const jCols = ["ID", "Dataset", "Policy", "Status", "CreatedAt"];
    const jRows = (report.jobs || []).map((j:any) => [
      String(j.id),
      String(j.datasetId),
      String(j.policyId),
      String(j.status),
      j.createdAt ? new Date(j.createdAt).toLocaleString() : ""
    ]);
    autoTable(doc as any, {
      startY: 80,
      head: [jCols],
      body: jRows,
      theme: "grid",
      styles: { fontSize: 9 }
    });

    // Append a short audit snippet page
    doc.addPage();
    doc.setFontSize(12);
    doc.text("Audit Highlights", margin, 60);
    const auditRows = (report.audits || []).slice(0, 30).map((a:any) => [
      new Date(a.timestamp).toLocaleString(),
      a.userEmail || "",
      a.action,
      a.resource || "",
      typeof a.details === "string" ? a.details : JSON.stringify(a.details || {})
    ]);
    autoTable(doc as any, {
      startY: 80,
      head: [["Timestamp","User","Action","Resource","Details"]],
      body: auditRows,
      styles: { fontSize: 8 }
    });

    // Footer
    const now = new Date();
    const filename = `compliance-report-${report.metadata.reportType}-${now.toISOString().slice(0,19).replace(/:/g,"-")}.pdf`;
    doc.save(filename);
  };

  const toggleSelectDataset = (id: string) => {
    setSelectedDatasets(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  };
  const toggleSelectPolicy = (id: string) => {
    setSelectedPolicies(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <Header />
      <main className="max-w-5xl mx-auto p-6">

        <h2 className="text-2xl font-bold mb-4">Compliance Report Generator</h2>

        <div className="bg-white p-6 rounded-xl shadow border mb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <div>
              <label className="block text-sm font-medium">Report Type</label>
              <select className="p-2 border rounded w-full" value={reportType} onChange={e => setReportType(e.target.value as ReportType)}>
                <option value="gdpr">GDPR</option>
                <option value="hipaa">HIPAA</option>
                <option value="pia">Privacy Impact Assessment (PIA)</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium">Date From</label>
              <input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="p-2 border rounded w-full" />
            </div>

            <div>
              <label className="block text-sm font-medium">Date To</label>
              <input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="p-2 border rounded w-full" />
            </div>
          </div>

          <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium mb-2">Datasets (pick any)</label>
              <div className="max-h-48 overflow-auto border rounded p-2">
                {datasets.map(d => (
                  <label key={d._id} className="flex items-center space-x-2">
                    <input type="checkbox" checked={selectedDatasets.includes(d._id)} onChange={()=>toggleSelectDataset(d._id)} />
                    <span className="text-sm">{d.originalName} <span className="text-xs text-gray-400">({d.uploadedBy})</span></span>
                  </label>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">Policies (pick any)</label>
              <div className="max-h-48 overflow-auto border rounded p-2">
                {policies.map(p => (
                  <label key={p._id} className="flex items-center space-x-2">
                    <input type="checkbox" checked={selectedPolicies.includes(p._id)} onChange={()=>toggleSelectPolicy(p._id)} />
                    <span className="text-sm">{p.policyName} <span className="text-xs text-gray-400">v{p.version}</span></span>
                  </label>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-4 flex items-center gap-3">
            <button onClick={submitGenerate} className="px-4 py-2 bg-cyan-600 text-white rounded">Generate Report</button>
            <button disabled={!report} onClick={exportPdf} className="px-4 py-2 bg-emerald-600 text-white rounded">Export PDF</button>
            <button onClick={()=>{ setReport(null); setSelectedDatasets([]); setSelectedPolicies([]); }} className="px-4 py-2 bg-gray-200 rounded">Reset</button>
          </div>
        </div>

        {/* Preview */}
        {loading && <div>Generating report...</div>}
        {report && (
          <div className="bg-white p-6 rounded-xl shadow border">
            <h3 className="font-bold text-lg">Preview: {report.metadata.reportType.toUpperCase()}</h3>
            <p className="text-sm text-gray-600">Generated at {new Date(report.metadata.generatedAt).toLocaleString()}</p>

            <div className="mt-4">
              <h4 className="font-semibold">Summary</h4>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-2">
                <div className="p-3 border rounded"><div className="text-xs text-gray-600">Datasets</div><div className="font-bold">{report.datasets.length}</div></div>
                <div className="p-3 border rounded"><div className="text-xs text-gray-600">Policies</div><div className="font-bold">{report.policies.length}</div></div>
                <div className="p-3 border rounded"><div className="text-xs text-gray-600">Jobs</div><div className="font-bold">{report.jobs.length}</div></div>
              </div>
            </div>

            <div className="mt-4">
              <h4 className="font-semibold">Findings</h4>
              {report.findings.length === 0 ? <p>No automated findings</p> : (
                <ul className="list-disc ml-6 mt-2">
                  {report.findings.map((f:any, idx:number) => <li key={idx}><strong>[{f.severity}]</strong> {f.message}</li>)}
                </ul>
              )}
            </div>

            <div className="mt-4">
              <h4 className="font-semibold">Audits (last 30)</h4>
              <div className="max-h-60 overflow-auto border rounded p-2">
                <table className="min-w-full text-sm">
                  <thead className="bg-gray-50"><tr><th className="p-2">Time</th><th className="p-2">User</th><th className="p-2">Action</th><th className="p-2">Hash</th></tr></thead>
                  <tbody>
                    {report.audits.slice(0,30).map((a:any, i:number) => (
                      <tr key={i} className="border-t">
                        <td className="p-2">{new Date(a.timestamp).toLocaleString()}</td>
                        <td className="p-2">{a.userEmail}</td>
                        <td className="p-2">{a.action}</td>
                        <td className="p-2 text-xs break-all">{a.hash}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

          </div>
        )}

      </main>
    </div>
  );
};

export default ComplianceReports;
